version: "3.7"

services:
  database:
    image: postgres
    container_name: db_fin_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
